{% set version = "0.1.9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-turner
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/turner_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/turner/turner_{{ version }}.tar.gz
  sha256: 182681bc0c16ab6a37c319c1165a4c4b4e70c476238ecb2f24e8cf3351008e61

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-tester
  run:
    - r-base
    - r-tester

test:
  commands:
    - $R -e "library('turner')"           # [not win]
    - "\"%R%\" -e \"library('turner')\""  # [win]

about:
  home: http://www.gastonsanchez.com
  license: GPL-3
  summary: Package designed for working with vectors and lists of vectors, mainly for turning them into other indexed data structures.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: turner
# Title: Turn vectors and lists of vectors into indexed structures
# Version: 0.1.7
# Date: 2014-02-17
# Author: Gaston Sanchez
# Maintainer: Gaston Sanchez <gaston.stat@gmail.com>
# Description: Package designed for working with vectors and lists of vectors, mainly for turning them into other indexed data structures.
# URL: http://www.gastonsanchez.com
# Depends: R (>= 3.0)
# Imports: tester
# Suggests: testthat, knitr
# VignetteBuilder: knitr
# License: GPL-3
# Collate: 'df_to_blocks.r' 'dummy_to_list.r' 'factor_to_dummy.r' 'from_to.r' 'funlist.r' 'indexify.r' 'lengths.r' 'list_ones.r' 'list_to_dummy.r' 'list_to_matrix.r' 'listify.r' 'listsize.r' 'matrix_to_blocks.r' 'vector_to_dummy.r' 'turner-package.r'
# Packaged: 2014-02-17 16:12:12 UTC; Gaston
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-02-17 17:35:09
