travis:
  secure:
    BINSTAR_TOKEN: i5lFOljkieIYY0uU/PNzMcekuaoPy5MC5HGpVavJvjS+FipSicYUC8KKSlT/Oi0KmgbFM6OCBHSzHGPfovJOPeUan4ngqNSlhfPhlXiAduxI7UQ2HCLaROEt+x2xIhmHO/iKKtALpTY99JJUb5zzqUpDL9upkIX0uTv+OkNZidx80kANT2zbrFZWbCj8AFzlG0PQrB4sKXbFLMvhuf3bvqrEH98EDquQ6imJW0uW2loOM/ohJP1iu//mNn1w02PR796QWfGjCH4gpo2MhKwcV/pethVSfI8q1C0tbXJxAlQbECM5oNy1/VELOB/w3KWmYT08/zstaS1d3TwN93DAydM/0lSMYUZKed854qPra8Rjp2YvZ3pkLixJ2880AiZy8GPUirELUhnNN+346JI5B24/SSQOsQIPgelaV+jY7+dBv+ieygnM+QKc8jv3ykBbV7yLmTQ9HEm4VlVEgZ69zlZpzFbPEn5Zj3ieXyohDFc9zmfTSvUwu5Gd5HiTSHfeXMd1SEprd7elkbbYs+LWrAOfq4CZC2PRA+W7mZbt6P27WtH2LuT7AGoZoKD937no7tVqLvugAGVUyREf/53qiQjtWGzxfIbx7nMGw9KUan0GE/uTaillxxVzDI+fRpHStm5jggOK0+JMJHboo1LXHOQGGaUFFIa9J+xpnpQe79s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
